import type { ModelMeta } from "./types"

export const mockModels: ModelMeta[] = [
  {
    id: "1",
    name: "Dragon Figurine",
    description: "A detailed dragon model perfect for tabletop gaming",
    tags: ["fantasy", "miniature", "dragon"],
    createdAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
    fileType: "generated",
    previewUrl: "/dragon-figurine-3d-model.jpg",
    glbUrl: "/models/dragon.glb",
    stlUrl: "/models/dragon.stl",
    printable: "printable",
    bboxMm: { x: 45, y: 32, z: 28 },
    volumeCm3: 12.5,
    areaCm2: 85.2,
    faces: 2840,
    material: { density_g_cm3: 1.24 },
    weight_g: 15.5,
    source: "nano-banana",
    version: 1,
  },
  {
    id: "2",
    name: "Mechanical Gear",
    description: "Functional gear for mechanical projects",
    tags: ["mechanical", "functional", "gear"],
    createdAt: "2024-01-14T15:45:00Z",
    updatedAt: "2024-01-14T15:45:00Z",
    fileType: "stl",
    previewUrl: "/mechanical-gear-3d-model.jpg",
    stlUrl: "/models/gear.stl",
    glbUrl: "/models/gear.glb",
    printable: "printable",
    bboxMm: { x: 30, y: 30, z: 8 },
    volumeCm3: 4.2,
    areaCm2: 45.8,
    faces: 1560,
    material: { density_g_cm3: 1.24 },
    weight_g: 5.2,
    source: "upload",
    version: 1,
  },
  {
    id: "3",
    name: "Organic Vase",
    description: "Flowing organic vase design",
    tags: ["organic", "vase", "decorative"],
    createdAt: "2024-01-13T09:20:00Z",
    updatedAt: "2024-01-13T09:20:00Z",
    fileType: "generated",
    previewUrl: "/organic-flowing-vase-3d-model.jpg",
    glbUrl: "/models/vase.glb",
    stlUrl: "/models/vase.stl",
    printable: "needs-fix",
    bboxMm: { x: 80, y: 80, z: 120 },
    volumeCm3: 185.6,
    areaCm2: 245.3,
    faces: 4280,
    material: { density_g_cm3: 1.24 },
    weight_g: 230.1,
    source: "nano-banana",
    version: 2,
  },
  {
    id: "4",
    name: "Low Poly Tree",
    description: "Stylized low poly tree for dioramas",
    tags: ["lowpoly", "nature", "tree"],
    createdAt: "2024-01-12T14:10:00Z",
    updatedAt: "2024-01-12T14:10:00Z",
    fileType: "obj",
    previewUrl: "/low-poly-tree-3d-model.jpg",
    objUrl: "/models/tree.obj",
    glbUrl: "/models/tree.glb",
    printable: "printable",
    bboxMm: { x: 25, y: 25, z: 40 },
    volumeCm3: 8.9,
    areaCm2: 62.4,
    faces: 890,
    material: { density_g_cm3: 1.24 },
    weight_g: 11.0,
    source: "upload",
    version: 1,
  },
  {
    id: "5",
    name: "Phone Stand",
    description: "Adjustable phone stand for desk use",
    tags: ["functional", "phone", "stand"],
    createdAt: "2024-01-11T11:30:00Z",
    updatedAt: "2024-01-11T11:30:00Z",
    fileType: "stl",
    previewUrl: "/phone-stand-3d-model.jpg",
    stlUrl: "/models/phone-stand.stl",
    glbUrl: "/models/phone-stand.glb",
    printable: "printable",
    bboxMm: { x: 85, y: 65, z: 45 },
    volumeCm3: 28.4,
    areaCm2: 156.7,
    faces: 1240,
    material: { density_g_cm3: 1.24 },
    weight_g: 35.2,
    source: "upload",
    version: 1,
  },
  {
    id: "6",
    name: "Abstract Sculpture",
    description: "Modern abstract sculpture piece",
    tags: ["abstract", "art", "sculpture"],
    createdAt: "2024-01-10T16:45:00Z",
    updatedAt: "2024-01-10T16:45:00Z",
    fileType: "generated",
    previewUrl: "/abstract-modern-sculpture-3d-model.jpg",
    glbUrl: "/models/sculpture.glb",
    stlUrl: "/models/sculpture.stl",
    printable: "printable",
    bboxMm: { x: 60, y: 40, z: 75 },
    volumeCm3: 45.8,
    areaCm2: 198.5,
    faces: 3560,
    material: { density_g_cm3: 1.24 },
    weight_g: 56.8,
    source: "nano-banana",
    version: 1,
  },
]

export const mockTags = ["fantasy", "mechanical", "organic", "lowpoly", "functional", "decorative", "miniature", "art"]

export const mockUser = {
  id: "user-1",
  email: "user@example.com",
  name: "John Doe",
  avatar: "/diverse-user-avatars.png",
}
